volumes:
  node_modules:

services:
  regular_redis:
    image: redis
    ports:
      - "36379:6379"

  bitnami_redis:
    platform: 'linux/amd64'
    user: root
    image: 'bitnami/redis:6.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "36380:6379"

  app:
    image: "node:alpine"
    depends_on:
      - regular_redis
      - bitnami_redis
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    working_dir: /app
    environment:
      - "REDIS_HOST=regular_redis"
      - "REDIS_PORT=6379"
      - "WAIT_UNTIL_READY=TRUE"
    command:
      - tail
      - -f
      - /dev/null
